version: '3'

services:
    ddrfuzz:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: base/ddrfuzz:latest

    mpg123:
        build:
            context: .
            dockerfile: ./projects/mpg123/Dockerfile
        image: mpg123/ddrfuzz:latest

    imagemagick:
        build:
            context: .
            dockerfile: ./projects/imagemagick/Dockerfile
        image: imagemagick/ddrfuzz:latest

    ffmpeg:
        build:
            context: .
            dockerfile: ./projects/ffmpeg/Dockerfile
        image: ffmpeg/ddrfuzz:latest

    libtiff:
        build:
            context: .
            dockerfile: ./projects/libtiff/Dockerfile
        image: libtiff/ddrfuzz:latest
