version: '3'

services:
    ddrfuzz:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: base/ddrfuzz:latest

    mpg123:
        build:
            context: .
            dockerfile: ./projects/mpg123/Dockerfile
        image: mpg123/ddrfuzz:latest

    imagemagick:
        build:
            context: .
            dockerfile: ./projects/imagemagick/Dockerfile
        image: imagemagick/ddrfuzz:latest

    libavif:
        build:
            context: ./projects/libavif
        image: libavif/ddrfuzz:latest

    libavc:
        build:
            context: ./projects/libavc
        image: libavc/ddrfuzz:latest

    libjpeg-turbo:
        build:
            context: ./projects/libjpeg-turbo
        image: libjpeg-turbo/ddrfuzz:latest

    ffmpeg:
        build:
            context: .
            dockerfile: ./projects/ffmpeg/Dockerfile
        image: ffmpeg/ddrfuzz:latest

    libtiff:
        build:
            context: .
            dockerfile: ./projects/libtiff/Dockerfile
        image: libtiff/ddrfuzz:latest

    libpng:
        build:
            context: .
            dockerfile: ./projects/libpng/Dockerfile
        image: libpng/ddrfuzz:latest

    libmpeg2:
        build:
            context: .
            dockerfile: ./projects/libmpeg2/Dockerfile
        image: libmpeg2/ddrfuzz:latest

    libspng:
        build:
            context: .
            dockerfile: ./projects/libspng/Dockerfile
        image: libspng/ddrfuzz:latest
