
FROM ddrfuzz:latest
MAINTAINER "Dongyoung Kim <ehddud758@gmail.com>"

RUN mkdir -p /src && cd /src 
WORKDIR /src 

RUN git clone https://android.googlesource.com/platform/external/libmpeg2
WORKDIR libmpeg2
