FROM base/ddrfuzz:latest
MAINTAINER "Sanghoon(Kevin) Jeon <kppw99@gmail.com>"


# Set Environment Variables
ENV CC=afl-gcc
ENV CXX=afl-g++
ARG home=/targets/mpg123
ARG pro_home=/tool/ddrfuzz/projects/mpg123

# Prerequisite
WORKDIR ${home}/seed/org/
WORKDIR ${home}/seed/copt/
WORKDIR ${home}/seed/topt/
WORKDIR ${home}/bin/
WORKDIR ${home}/source/
RUN apt-get -y install cron
RUN wget https://www.mpg123.de/snapshot
RUN tar -xvf snapshot --directory=${home}/source --strip-components=1
RUN rm -rf snapshot
WORKDIR /tool/ddrfuzz/
RUN git pull origin main


# Build Target Program
WORKDIR ${home}/source/build/
RUN cp -rf ${pro_home}/build_new.sh .
RUN bash build_new.sh cov


# Copy Seed Corpus and Fuzzing Executables
WORKDIR ${pro_home}
RUN tar -zxvf seed.tar.gz

RUN cp -rf ${pro_home}/seed/* ${home}/seed/org/
RUN cp -rf ${pro_home}/valuable_seed.tar.gz ${home}
RUN cp -rf ${home}/source/build/src/mpg123 ${home}/bin/

RUN cp -rf ${pro_home}/afl-ddrfuzz.sh ${home}
RUN cp -rf ${pro_home}/afl-fuzz.sh ${home}
RUN cp -rf ${pro_home}/opt-seed.sh ${home}
RUN cp -rf ${pro_home}/cov-test.sh ${home}

WORKDIR ${home}

RUN tar -zxvf valuable_seed.tar.gz
RUN (crontab -l 2>/dev/null; echo "*/10 * * * * /targets/ffmpeg/cov-test.sh -with args") | crontab -
RUN mkdir cov
RUN service cron start

# docker build -t mpg123_gcov/ddrfuzz:latest . -f Dockerfile_for_gcov
